-- UC33/RN42 - Colecoes agrupando decks (agrupamento tematico opcional, ex.:
-- "Medicina" reunindo os decks "Anatomia" e "Sistema Cardiovascular").
-- Excluir uma colecao NAO exclui os decks nela contidos - apenas desvincula
-- (ON DELETE SET NULL), diferente da cascata de exclusao de deck (RN13).

CREATE TABLE colecao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario (id) ON DELETE CASCADE,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
);

ALTER TABLE deck ADD COLUMN colecao_id BIGINT REFERENCES colecao (id) ON DELETE SET NULL;

CREATE INDEX idx_deck_colecao_id ON deck (colecao_id);
