-- Schema inicial, gerado a partir do que o Hibernate (ddl-auto=update) vem
-- criando desde o inicio do projeto. Este script foi conferido coluna a
-- coluna contra um banco Postgres real inicializado do zero pelas entidades
-- JPA atuais (Usuario, Deck, MaterialOrigem, Flashcard, RevisaoFlashcard,
-- Quiz, QuestaoQuiz, TentativaQuiz) - nao contra o que
-- docs/modelo-de-dados.md descreve. Onde os dois divergem, o comentario ao
-- lado da coluna/constraint aponta a divergencia (ver relatorio enviado ao
-- solicitar esta migration para decidir se o codigo ou a documentacao deve
-- mudar).
--
-- Nenhuma FK abaixo tem ON DELETE CASCADE: a exclusao em cascata da RN13 e
-- feita inteiramente pelo Hibernate (cascade = CascadeType.ALL,
-- orphanRemoval = true), nao pelo banco - diferente do que o DDL de
-- docs/modelo-de-dados.md sugere.

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL
);

CREATE TABLE deck (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario (id),
    titulo VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    criado_em TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL
);

CREATE TABLE material_origem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL REFERENCES deck (id),
    nome_arquivo VARCHAR(255) NOT NULL,
    caminho_arquivo VARCHAR(500) NOT NULL,
    texto_extraido TEXT,
    -- CHECK gerado automaticamente pelo Hibernate para @Enumerated(STRING)
    -- sob o dialeto Postgres (nao existe no H2, por isso passou
    -- despercebido nos testes @DataJpaTest).
    status_processamento VARCHAR(20) NOT NULL
        CONSTRAINT material_origem_status_processamento_check
        CHECK (status_processamento IN ('PENDENTE', 'PROCESSADO', 'ERRO')),
    criado_em TIMESTAMP(6) NOT NULL
);

CREATE TABLE flashcard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL REFERENCES deck (id),
    pergunta VARCHAR(1000) NOT NULL,
    resposta VARCHAR(1000) NOT NULL,
    mnemonico VARCHAR(500),
    origem VARCHAR(10) NOT NULL
        CONSTRAINT flashcard_origem_check
        CHECK (origem IN ('MANUAL', 'IA')),
    criado_em TIMESTAMP(6) NOT NULL
);

CREATE TABLE revisao_flashcard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flashcard_id BIGINT NOT NULL REFERENCES flashcard (id),
    usuario_id BIGINT NOT NULL REFERENCES usuario (id),
    data_revisao TIMESTAMP(6) NOT NULL,
    qualidade_resposta INTEGER NOT NULL,
    -- Sem CHECK (qualidade_resposta BETWEEN 0 AND 5): RN09 e validada via
    -- Bean Validation no DTO (AvaliarRespostaRequestDTO), nao no banco.
    fator_facilidade NUMERIC(3, 2) NOT NULL,
    -- Sem CHECK (fator_facilidade >= 1.3): RN12 e garantida pelo
    -- Sm2CalculatorService, nao no banco.
    intervalo_dias INTEGER NOT NULL,
    repeticoes INTEGER NOT NULL,
    proxima_revisao DATE NOT NULL
);

CREATE TABLE quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL REFERENCES deck (id),
    titulo VARCHAR(150) NOT NULL,
    criado_em TIMESTAMP(6) NOT NULL
);

CREATE TABLE questao_quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL REFERENCES quiz (id),
    enunciado VARCHAR(1000) NOT NULL,
    -- Divergencia: docs/modelo-de-dados.md documenta "alternativas" como
    -- JSONB. O AlternativasConverter (Jackson) grava uma string JSON numa
    -- coluna comum, e o @Column da entidade declara columnDefinition =
    -- "TEXT" - o tipo real da coluna e TEXT, nao jsonb.
    alternativas TEXT NOT NULL,
    resposta_correta VARCHAR(500) NOT NULL
);

CREATE TABLE tentativa_quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id BIGINT NOT NULL REFERENCES quiz (id),
    usuario_id BIGINT NOT NULL REFERENCES usuario (id),
    data_tentativa TIMESTAMP(6) NOT NULL,
    pontuacao NUMERIC(5, 2) NOT NULL
);
