-- UC27/RN35/RN36 - Provas personalizadas via IA: usuario escolhe
-- flashcard(s) e um estilo de prova (ENEM/Vestibular/Conhecimentos Gerais);
-- questoes sao ineditas (nao repetem o flashcard) e trazem uma explicacao;
-- o historico guarda o detalhamento por questao de cada tentativa.

ALTER TABLE quiz ADD COLUMN origem VARCHAR(20) NOT NULL DEFAULT 'DETERMINISTICO';
ALTER TABLE quiz ADD CONSTRAINT quiz_origem_check
    CHECK (origem IN ('DETERMINISTICO', 'IA_PERSONALIZADA'));

ALTER TABLE quiz ADD COLUMN estilo VARCHAR(20);
ALTER TABLE quiz ADD CONSTRAINT quiz_estilo_check
    CHECK (estilo IS NULL OR estilo IN ('ENEM', 'VESTIBULAR', 'GERAL'));

ALTER TABLE questao_quiz ADD COLUMN explicacao TEXT;

CREATE TABLE resposta_tentativa_quiz (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tentativa_quiz_id BIGINT NOT NULL REFERENCES tentativa_quiz (id) ON DELETE CASCADE,
    questao_quiz_id BIGINT NOT NULL REFERENCES questao_quiz (id) ON DELETE CASCADE,
    alternativa_escolhida VARCHAR(500) NOT NULL,
    correta BOOLEAN NOT NULL
);
