-- UC29/RN37/RN38 - Compartilhar deck via link publico somente leitura.
-- Cada deck tem no maximo um link ativo por vez (reativar apos revogar
-- gera um novo token, invalidando o anterior).

CREATE TABLE compartilhamento_deck (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deck_id BIGINT NOT NULL UNIQUE REFERENCES deck (id) ON DELETE CASCADE,
    token VARCHAR(36) NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    revogado_em TIMESTAMP
);

CREATE INDEX idx_compartilhamento_deck_token ON compartilhamento_deck (token);
